In [1]:
import numpy as np 
import pandas as pd

In [2]:

df = pd.read_csv('../data/fraud_data.csv')

In [9]:
df.head(20)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
5,5.586408,13.261073,0.064768,1.0,0.0,0.0,0.0,0.0
6,3.724019,0.956838,0.278465,1.0,0.0,0.0,1.0,0.0
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
8,0.876632,2.503609,1.516999,0.0,0.0,0.0,0.0,0.0
9,8.839047,2.970512,2.361683,1.0,0.0,0.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0
12,765.282559,0.371562,0.551245,1.0,1.0,0.0,0.0,0.0
13,2.131956,56.372401,6.358667,1.0,0.0,0.0,1.0,1.0
14,13.955972,0.271522,2.798901,1.0,0.0,0.0,1.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0,0.0
16,114.519789,0.707003,0.516990,1.0,0.0,0.0,0.0,0.0
17,3.589649,6.247458,1.846451,1.0,0.0,0.0,0.0,0.0
18,11.085152,34.661351,2.530758,1.0,0.0,0.0,1.0,0.0
19,6.194671,1.142014,0.307217,1.0,0.0,0.0,0.0,0.0

In [4]:
df.shape

(500000, 8)

In [5]:
df['fraud'].value_counts()

fraud
0.0    456333
1.0     43667
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 8 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   distance_from_home              500000 non-null  float64
 1   distance_from_last_transaction  500000 non-null  float64
 2   ratio_to_median_purchase_price  500000 non-null  float64
 3   repeat_retailer                 500000 non-null  float64
 4   used_chip                       500000 non-null  float64
 5   used_pin_number                 500000 non-null  float64
 6   online_order                    500000 non-null  float64
 7   fraud                           500000 non-null  float64
dtypes: float64(8)
memory usage: 30.5 MB

In [7]:
df.columns

Index(['distance_from_home', 'distance_from_last_transaction',
       'ratio_to_median_purchase_price', 'repeat_retailer', 'used_chip',
       'used_pin_number', 'online_order', 'fraud'],
      dtype='object')

In [8]:
df.describe()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
count,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,26.683361,5.024226,1.825429,0.881668,0.350544,0.101366,0.651040,0.087334
std,65.922348,28.121703,2.821275,0.323001,0.477141,0.301813,0.476642,0.282324
min,0.004874,0.000407,0.004399,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.880415,0.296336,0.475681,1.000000,0.000000,0.000000,0.000000,0.000000
50%,9.986540,0.997728,0.998895,1.000000,0.000000,0.000000,1.000000,0.000000
75%,25.811361,3.352337,2.100906,1.000000,1.000000,0.000000,1.000000,0.000000
max,10632.723672,11851.104565,267.802942,1.000000,1.000000,1.000000,1.000000,1.000000